
pol_mapper = {
    "Not Applicable": "NA",
    "Related to Politically Exposed Person": "RPEP",
    "Politically Exposed Person": "PEP"
}

tin_mapper = {
    "Student": "01",
    "Home-maker": "02",
    "House-Wife": "03",
    "Retired": "04",
    "Diplomat": "05",
    "TIN Not Eligible as of now NA.": "06"
}

country_mapper = {
    "Afghanistan": "AF",
    "Åland Islands": "AX",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica [b]": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia [c]": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas (the)": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia (Plurinational State of)": "BO",
    "Bonaire": "BQ",
    "Sint Eustatius": "",
    "Saba": "",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory (the)": "IO",
    "British Virgin Islands – See Virgin Islands (British)": "",
    "Brunei Darussalam [f]": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burma – See Myanmar": "",
    "Burundi": "BI",
    "Cabo Verde [g]": "CV",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde – See Cabo Verde": "",
    "Caribbean Netherlands – See Bonaire, Sint Eustatius and Saba": "",
    "Cayman Islands (the)": "KY",
    "Central African Republic (the)": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "China, The Republic of – See Taiwan (Province of China)": "",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands (the)": "CC",
    "Colombia": "CO",
    "Comoros (the)": "KM",
    "Congo (the Democratic Republic of the)": "CD",
    "Congo (the) [h]": "CG",
    "Cook Islands (the)": "CK",
    "Costa Rica": "CR",
    "Côte d'Ivoire [i]": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Cyprus": "CY",
    "Czechia [j]": "CZ",
    "Democratic People's Republic of Korea – See Korea, The Democratic People's Republic of": "",
    "Democratic Republic of the Congo – See Congo, The Democratic Republic of the": "",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic (the)": "DO",
    "East Timor – See Timor-Leste": "",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini [k]": "SZ",
    "Ethiopia": "ET",
    "Falkland Islands (the) [Malvinas] [l]": "FK",
    "Faroe Islands (the)": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France [m]": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories (the) [n]": "TF",
    "Gabon": "GA",
    "Gambia (the)": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Great Britain – See United Kingdom, The": "",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and McDonald Islands": "HM",
    "Holy See (the) [o]": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran (Islamic Republic of)": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast – See Côte d'Ivoire": "",
    "Jamaica": "JM",
    "Jan Mayen – See Svalbard and Jan Mayen": "",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea (the Democratic People's Republic of) [p]": "KP",
    "Korea (the Republic of) [q]": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic (the) [r]": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao [s]": "MO",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands (the)": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia (Federated States of)": "FM",
    "Moldova (the Republic of)": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar [t]": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands, Kingdom of the": "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger (the)": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "North Korea – See Korea, The Democratic People's Republic of": "",
    "North Macedonia [u]": "MK",
    "Northern Mariana Islands (the)": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestine, State of": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "People's Republic of China – See China": "",
    "Peru": "PE",
    "Philippines (the)": "PH",
    "Pitcairn [v]": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Republic of China – See Taiwan (Province of China)": "",
    "Republic of Korea – See Korea, The Republic of": "",
    "Republic of the Congo – See Congo, The": "",
    "Réunion": "RE",
    "Romania": "RO",
    "Russian Federation (the) [w]": "RU",
    "Rwanda": "RW",
    "Saba – See Bonaire, Sint Eustatius and Saba": "",
    "Sahrawi Arab Democratic Republic – See Western Sahara": "",
    "Saint Barthélemy": "BL",
    "Saint Helena": "SH",
    "Ascension Island": "",
    "Tristan da Cunha": "",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin (French part)": "MF",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Eustatius – See Bonaire, Sint Eustatius and Saba": "",
    "Sint Maarten (Dutch part)": "SX",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Korea – See Korea, The Republic of": "",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan (the)": "SD",
    "Suriname": "SR",
    "Svalbard": "SJ",
    "Jan Mayen": "",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic (the) [y]": "SY",
    "Taiwan (Province of China) [z]": "TW",
    "Tajikistan": "TJ",
    "Tanzania, the United Republic of": "TZ",
    "Thailand": "TH",
    "Timor-Leste [ab]": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Türkiye [ac]": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands (the)": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates (the)": "AE",
    "United Kingdom of Great Britain and Northern Ireland (the)": "GB",
    "United States Minor Outlying Islands (the) [ae]": "UM",
    "United States of America (the)": "US",
    "United States Virgin Islands – See Virgin Islands (U.S.)": "",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatican City – See Holy See, The": "",
    "Venezuela (Bolivarian Republic of)": "VE",
    "Viet Nam [ag]": "VN",
    "Virgin Islands (British) [ah]": "VG",
    "Virgin Islands (U.S.) [ai]": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara [aj]": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
}

