pol_mapper  = {
  "NA": "Not Applicable",
  "RPEP": "Related to Politically Exposed Person",
  "PEP": "Politically Exposed Person"
}

tin_mapper = {
  "01": "Student",
  "02": "Home-maker",
  "03": "House-Wife",
  "04": "Retired",
  "05": "Diplomat",
  "06": "TIN Not Eligible as of now NA."
}

country_mapper = {
    "AF": "Afghanistan",
    "AX": "Åland Islands",
    "AL": "Albania",
    "DZ": "Algeria",
    "AS": "American Samoa",
    "AD": "Andorra",
    "AO": "Angola",
    "AI": "Anguilla",
    "AQ": "Antarctica [b]",
    "AG": "Antigua and Barbuda",
    "AR": "Argentina",
    "AM": "Armenia",
    "AW": "Aruba",
    "AU": "Australia [c]",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas (the)",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BM": "Bermuda",
    "BT": "Bhutan",
    "BO": "Bolivia (Plurinational State of)",
    "BQ": "Bonaire",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BV": "Bouvet Island",
    "BR": "Brazil",
    "IO": "British Indian Ocean Territory (the)",
    "BN": "Brunei Darussalam [f]",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Cabo Verde [g]",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "KY": "Cayman Islands (the)",
    "CF": "Central African Republic (the)",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CX": "Christmas Island",
    "CC": "Cocos (Keeling) Islands (the)",
    "CO": "Colombia",
    "KM": "Comoros (the)",
    "CD": "Congo (the Democratic Republic of the)",
    "CG": "Congo (the) [h]",
    "CK": "Cook Islands (the)",
    "CR": "Costa Rica",
    "CI": "Côte d'Ivoire [i]",
    "HR": "Croatia",
    "CU": "Cuba",
    "CW": "Curaçao",
    "CY": "Cyprus",
    "CZ": "Czechia [j]",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic (the)",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "SZ": "Eswatini [k]",
    "ET": "Ethiopia",
    "FK": "Falkland Islands (the) [Malvinas] [l]",
    "FO": "Faroe Islands (the)",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France [m]",
    "GF": "French Guiana",
    "PF": "French Polynesia",
    "TF": "French Southern Territories (the) [n]",
    "GA": "Gabon",
    "GM": "Gambia (the)",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GI": "Gibraltar",
    "GR": "Greece",
    "GL": "Greenland",
    "GD": "Grenada",
    "GP": "Guadeloupe",
    "GU": "Guam",
    "GT": "Guatemala",
    "GG": "Guernsey",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HM": "Heard Island and McDonald Islands",
    "VA": "Holy See (the) [o]",
    "HN": "Honduras",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran (Islamic Republic of)",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IM": "Isle of Man",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JE": "Jersey",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea (the Democratic People's Republic of) [p]",
    "KR": "Korea (the Republic of) [q]",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Lao People's Democratic Republic (the) [r]",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MO": "Macao [s]",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands (the)",
    "MQ": "Martinique",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "YT": "Mayotte",
    "MX": "Mexico",
    "FM": "Micronesia (Federated States of)",
    "MD": "Moldova (the Republic of)",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MS": "Montserrat",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar [t]",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands, Kingdom of the",
    "NC": "New Caledonia",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger (the)",
    "NG": "Nigeria",
    "NU": "Niue",
    "NF": "Norfolk Island",
    "MK": "North Macedonia [u]",
    "MP": "Northern Mariana Islands (the)",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestine, State of",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines (the)",
    "PN": "Pitcairn [v]",
    "PL": "Poland",
    "PT": "Portugal",
    "PR": "Puerto Rico",
    "QA": "Qatar",
    "RE": "Réunion",
    "RO": "Romania",
    "RU": "Russian Federation (the) [w]",
    "RW": "Rwanda",
    "BL": "Saint Barthélemy",
    "SH": "Saint Helena",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "MF": "Saint Martin (French part)",
    "PM": "Saint Pierre and Miquelon",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SX": "Sint Maarten (Dutch part)",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "GS": "South Georgia and the South Sandwich Islands",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan (the)",
    "SR": "Suriname",
    "SJ": "Svalbard",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syrian Arab Republic (the) [y]",
    "TW": "Taiwan (Province of China) [z]",
    "TJ": "Tajikistan",
    "TZ": "Tanzania, the United Republic of",
    "TH": "Thailand",
    "TL": "Timor-Leste [aa]",
    "TG": "Togo",
    "TK": "Tokelau",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TC": "Turks and Caicos Islands (the)",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates (the)",
    "GB": "United Kingdom",
    "US": "United States of America (the)",
    "UM": "United States Minor Outlying Islands (the)",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VE": "Venezuela (Bolivarian Republic of)",
    "VN": "Viet Nam",
    "VG": "Virgin Islands (British)",
    "VI": "Virgin Islands (U.S.)",
    "WF": "Wallis and Futuna",
    "EH": "Western Sahara [ae]",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe"
}


old_country_mapper = {
    "Afghanistan": "AF",
    "Åland Islands": "AX",
    "Albania": "AL",
    "Algeria": "DZ",
    "American Samoa": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguilla": "AI",
    "Antarctica [b]": "AQ",
    "Antigua and Barbuda": "AG",
    "Argentina": "AR",
    "Armenia": "AM",
    "Aruba": "AW",
    "Australia [c]": "AU",
    "Austria": "AT",
    "Azerbaijan": "AZ",
    "Bahamas (the)": "BS",
    "Bahrain": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Belarus": "BY",
    "Belgium": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermuda": "BM",
    "Bhutan": "BT",
    "Bolivia (Plurinational State of)": "BO",
    "Bonaire": "BQ",
    "Sint Eustatius": "",
    "Saba": "",
    "Bosnia and Herzegovina": "BA",
    "Botswana": "BW",
    "Bouvet Island": "BV",
    "Brazil": "BR",
    "British Indian Ocean Territory (the)": "IO",
    "British Virgin Islands – See Virgin Islands (British)": "",
    "Brunei Darussalam [f]": "BN",
    "Bulgaria": "BG",
    "Burkina Faso": "BF",
    "Burma – See Myanmar": "",
    "Burundi": "BI",
    "Cabo Verde [g]": "CV",
    "Cambodia": "KH",
    "Cameroon": "CM",
    "Canada": "CA",
    "Cape Verde – See Cabo Verde": "",
    "Caribbean Netherlands – See Bonaire, Sint Eustatius and Saba": "",
    "Cayman Islands (the)": "KY",
    "Central African Republic (the)": "CF",
    "Chad": "TD",
    "Chile": "CL",
    "China": "CN",
    "China, The Republic of – See Taiwan (Province of China)": "",
    "Christmas Island": "CX",
    "Cocos (Keeling) Islands (the)": "CC",
    "Colombia": "CO",
    "Comoros (the)": "KM",
    "Congo (the Democratic Republic of the)": "CD",
    "Congo (the) [h]": "CG",
    "Cook Islands (the)": "CK",
    "Costa Rica": "CR",
    "Côte d'Ivoire [i]": "CI",
    "Croatia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Cyprus": "CY",
    "Czechia [j]": "CZ",
    "Democratic People's Republic of Korea – See Korea, The Democratic People's Republic of": "",
    "Democratic Republic of the Congo – See Congo, The Democratic Republic of the": "",
    "Denmark": "DK",
    "Djibouti": "DJ",
    "Dominica": "DM",
    "Dominican Republic (the)": "DO",
    "East Timor – See Timor-Leste": "",
    "Ecuador": "EC",
    "Egypt": "EG",
    "El Salvador": "SV",
    "Equatorial Guinea": "GQ",
    "Eritrea": "ER",
    "Estonia": "EE",
    "Eswatini [k]": "SZ",
    "Ethiopia": "ET",
    "Falkland Islands (the) [Malvinas] [l]": "FK",
    "Faroe Islands (the)": "FO",
    "Fiji": "FJ",
    "Finland": "FI",
    "France [m]": "FR",
    "French Guiana": "GF",
    "French Polynesia": "PF",
    "French Southern Territories (the) [n]": "TF",
    "Gabon": "GA",
    "Gambia (the)": "GM",
    "Georgia": "GE",
    "Germany": "DE",
    "Ghana": "GH",
    "Gibraltar": "GI",
    "Great Britain – See United Kingdom, The": "",
    "Greece": "GR",
    "Greenland": "GL",
    "Grenada": "GD",
    "Guadeloupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guinea": "GN",
    "Guinea-Bissau": "GW",
    "Guyana": "GY",
    "Haiti": "HT",
    "Heard Island and McDonald Islands": "HM",
    "Holy See (the) [o]": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungary": "HU",
    "Iceland": "IS",
    "India": "IN",
    "Indonesia": "ID",
    "Iran (Islamic Republic of)": "IR",
    "Iraq": "IQ",
    "Ireland": "IE",
    "Isle of Man": "IM",
    "Israel": "IL",
    "Italy": "IT",
    "Ivory Coast – See Côte d'Ivoire": "",
    "Jamaica": "JM",
    "Jan Mayen – See Svalbard and Jan Mayen": "",
    "Japan": "JP",
    "Jersey": "JE",
    "Jordan": "JO",
    "Kazakhstan": "KZ",
    "Kenya": "KE",
    "Kiribati": "KI",
    "Korea (the Democratic People's Republic of) [p]": "KP",
    "Korea (the Republic of) [q]": "KR",
    "Kuwait": "KW",
    "Kyrgyzstan": "KG",
    "Lao People's Democratic Republic (the) [r]": "LA",
    "Latvia": "LV",
    "Lebanon": "LB",
    "Lesotho": "LS",
    "Liberia": "LR",
    "Libya": "LY",
    "Liechtenstein": "LI",
    "Lithuania": "LT",
    "Luxembourg": "LU",
    "Macao [s]": "MO",
    "Madagascar": "MG",
    "Malawi": "MW",
    "Malaysia": "MY",
    "Maldives": "MV",
    "Mali": "ML",
    "Malta": "MT",
    "Marshall Islands (the)": "MH",
    "Martinique": "MQ",
    "Mauritania": "MR",
    "Mauritius": "MU",
    "Mayotte": "YT",
    "Mexico": "MX",
    "Micronesia (Federated States of)": "FM",
    "Moldova (the Republic of)": "MD",
    "Monaco": "MC",
    "Mongolia": "MN",
    "Montenegro": "ME",
    "Montserrat": "MS",
    "Morocco": "MA",
    "Mozambique": "MZ",
    "Myanmar [t]": "MM",
    "Namibia": "NA",
    "Nauru": "NR",
    "Nepal": "NP",
    "Netherlands, Kingdom of the": "NL",
    "New Caledonia": "NC",
    "New Zealand": "NZ",
    "Nicaragua": "NI",
    "Niger (the)": "NE",
    "Nigeria": "NG",
    "Niue": "NU",
    "Norfolk Island": "NF",
    "North Korea – See Korea, The Democratic People's Republic of": "",
    "North Macedonia [u]": "MK",
    "Northern Mariana Islands (the)": "MP",
    "Norway": "NO",
    "Oman": "OM",
    "Pakistan": "PK",
    "Palau": "PW",
    "Palestine, State of": "PS",
    "Panama": "PA",
    "Papua New Guinea": "PG",
    "Paraguay": "PY",
    "People's Republic of China – See China": "",
    "Peru": "PE",
    "Philippines (the)": "PH",
    "Pitcairn [v]": "PN",
    "Poland": "PL",
    "Portugal": "PT",
    "Puerto Rico": "PR",
    "Qatar": "QA",
    "Republic of China – See Taiwan (Province of China)": "",
    "Republic of Korea – See Korea, The Republic of": "",
    "Republic of the Congo – See Congo, The": "",
    "Réunion": "RE",
    "Romania": "RO",
    "Russian Federation (the) [w]": "RU",
    "Rwanda": "RW",
    "Saba – See Bonaire, Sint Eustatius and Saba": "",
    "Sahrawi Arab Democratic Republic – See Western Sahara": "",
    "Saint Barthélemy": "BL",
    "Saint Helena": "SH",
    "Ascension Island": "",
    "Tristan da Cunha": "",
    "Saint Kitts and Nevis": "KN",
    "Saint Lucia": "LC",
    "Saint Martin (French part)": "MF",
    "Saint Pierre and Miquelon": "PM",
    "Saint Vincent and the Grenadines": "VC",
    "Samoa": "WS",
    "San Marino": "SM",
    "Sao Tome and Principe": "ST",
    "Saudi Arabia": "SA",
    "Senegal": "SN",
    "Serbia": "RS",
    "Seychelles": "SC",
    "Sierra Leone": "SL",
    "Singapore": "SG",
    "Sint Eustatius – See Bonaire, Sint Eustatius and Saba": "",
    "Sint Maarten (Dutch part)": "SX",
    "Slovakia": "SK",
    "Slovenia": "SI",
    "Solomon Islands": "SB",
    "Somalia": "SO",
    "South Africa": "ZA",
    "South Georgia and the South Sandwich Islands": "GS",
    "South Korea – See Korea, The Republic of": "",
    "South Sudan": "SS",
    "Spain": "ES",
    "Sri Lanka": "LK",
    "Sudan (the)": "SD",
    "Suriname": "SR",
    "Svalbard": "SJ",
    "Jan Mayen": "",
    "Sweden": "SE",
    "Switzerland": "CH",
    "Syrian Arab Republic (the) [y]": "SY",
    "Taiwan (Province of China) [z]": "TW",
    "Tajikistan": "TJ",
    "Tanzania, the United Republic of": "TZ",
    "Thailand": "TH",
    "Timor-Leste [ab]": "TL",
    "Togo": "TG",
    "Tokelau": "TK",
    "Tonga": "TO",
    "Trinidad and Tobago": "TT",
    "Tunisia": "TN",
    "Türkiye [ac]": "TR",
    "Turkmenistan": "TM",
    "Turks and Caicos Islands (the)": "TC",
    "Tuvalu": "TV",
    "Uganda": "UG",
    "Ukraine": "UA",
    "United Arab Emirates (the)": "AE",
    "United Kingdom of Great Britain and Northern Ireland (the)": "GB",
    "United States Minor Outlying Islands (the) [ae]": "UM",
    "United States of America (the)": "US",
    "United States Virgin Islands – See Virgin Islands (U.S.)": "",
    "Uruguay": "UY",
    "Uzbekistan": "UZ",
    "Vanuatu": "VU",
    "Vatican City – See Holy See, The": "",
    "Venezuela (Bolivarian Republic of)": "VE",
    "Viet Nam [ag]": "VN",
    "Virgin Islands (British) [ah]": "VG",
    "Virgin Islands (U.S.) [ai]": "VI",
    "Wallis and Futuna": "WF",
    "Western Sahara [aj]": "EH",
    "Yemen": "YE",
    "Zambia": "ZM",
    "Zimbabwe": "ZW",
}

state_master = {
    "003": "PUNJAB",
    "002": "HIMACHAL PRADESH",
    "001": "JAMMU AND KASHMIR",
    "004": "CHANDIGARH",
    "005": "UTTARAKHAND",
    "006": "HARYANA",
    "007": "DELHI",
    "008": "RAJASTHAN",
    "009": "UTTAR PRADESH",
    "010": "BIHAR",
    "011": "SIKKIM",
    "012": "ARUNACHAL PRADESH",
    "013": "ASSAM",
    "014": "MANIPUR",
    "015": "MIZORAM",
    "016": "TRIPURA",
    "017": "MEGHALAYA",
    "018": "NAGALAND",
    "019": "WEST BENGAL",
    "020": "JHARKHAND",
    "021": "ODISHA",
    "022": "CHHATTISGARH",
    "023": "MADHYA PRADESH",
    "024": "GUJARAT",
    "025": "DAMAN AND DIU",
    "026": "DADRA AND NAGAR HAVELI",
    "027": "MAHARASHTRA",
    "028": "ANDHRA PRADESH",
    "029": "KARNATAKA",
    "030": "GOA",
    "031": "LAKSHADWEEP",
    "032": "KERALA",
    "033": "TAMIL NADU",
    "034": "PUDUCHERRY",
    "035": "ANDAMAN AND NICOBAR ISLANDS",
    "099": "OTHERS",
    "037": "TELANGANA"
}
